src/lase/servlet/AnswerBean.java
package lase.servlet;

import java.io.Serializable;

/**
 * JavaBean s odpovědí nalezenou systémem LASE určený pro zobrazení odpovědi na
 * webové stránce.
 * 
 * @author Rudolf Šíma
 * 
 */
public class AnswerBean implements Serializable {
	private static final long serialVersionUID = 7590379439616421151L;
	
	
	/**
	 * Krátká forma nalezené odpovědi.
	 */
	private String shortAnswer;
	
	/**
	 * Dlouhá forma nalezení odpovědi.
	 */
	private String longAnswer;
	
	/**
	 * URL stránky, ze které nalezená odpověď pochází.
	 */
	private String sourceUrl;
	
	/**
	 * Titulek stránky, ze které nalezená odpověď pochází.
	 */
	private String sourceTitle;
	
	/**
	 * Udává, zda je obsah této třídy platný.
	 */
	private boolean valid;
	
	/**
	 * Udává, že odpověď nebyla nalezena.
	 */
	private boolean notFound;
	
	/**
	 * Vytvoří novou instancí {@code AnswerBean}.
	 */
	public AnswerBean() {
	}

	/**
	 * Vrací {@code true} nebyla-li odpověď nalezena. Byla-li nalezena, vrací
	 * {@code false}.
	 * 
	 * @return Vrací {@code true} nebyla-li odpověď nalezena. Byla-li nalezena,
	 *         vrací {@code false}.
	 */
	public boolean isNotFound() {
		return notFound;
	}

	/**
	 * Nastaví hodnotu udávající, zda odpověď NEbyla nalezena ({@code true}
	 * znamená, že NEbyla).
	 * 
	 * @param notFound
	 *            Hodnota udávající, zda odpověď NEbyla nalezena.
	 */
	public void setNotFound(boolean notFound) {
		this.notFound = notFound;
	}

	/**
	 * Vrací krátkou formu nalezené odpovědi.
	 * 
	 * @return Vrací krátkou formu nalezené odpovědi.
	 */
	public String getShortAnswer() {
		return shortAnswer;
	}

	/**
	 * Nastaví krátkou formu odpovědi.
	 * 
	 * @param shortAnswer
	 *            Nová krátká forma odpovědi.
	 */
	public void setShortAnswer(String shortAnswer) {
		this.shortAnswer = shortAnswer;
	}

	/**
	 * Vrací dlouhou formu nalezené odpovědi.
	 * 
	 * @return Vrací formu odpovědi.
	 */
	public String getLongAnswer() {
		return longAnswer;
	}

	/**
	 * Nastaví dlouhou formu nalezené odpovědi.
	 * 
	 * @param longAnswer
	 *            Nová dlouhá forma nalezené odpovědi.
	 */
	public void setLongAnswer(String longAnswer) {
		this.longAnswer = longAnswer;
	}

	/**
	 * Vrací URL stránky, na které byla odpověď nalezena.
	 * 
	 * @return Vrací URL stránky, na které byla odpověď nalezena.
	 */
	public String getSourceUrl() {
		return sourceUrl;
	}

	/**
	 * Nastaví URL stránky, na které byla odpověď nalezena.
	 * 
	 * @param sourceUrl
	 *            URL stránky na které byla odpověď nalezena.
	 * 
	 */
	public void setSourceUrl(String sourceUrl) {
		this.sourceUrl = sourceUrl;
	}

	/**
	 * Vrací titulek stránky na které byla odpověď nalezena.
	 * 
	 * @return Vrací titulek stránky na které byla odpověď nalezena.
	 */
	public String getSourceTitle() {
		return sourceTitle;
	}

	/**
	 * Nastaví titulek stránky, na které byla odpověď nalezena.
	 * 
	 * @param sourceTitle
	 *            Nový titulek stránky, na které byla odpověď nalezena.
	 */
	public void setSourceTitle(String sourceTitle) {
		this.sourceTitle = sourceTitle;
	}

	/** Zjistí, zda je obsah této třídy platný.
	 * 
	 * @return Vrací {@code true}, je-li obsah této třídy platný. Jinak vrací {@code false}.
	 */
	public boolean isValid() {
		return valid;
	}

	/**
	 * Nastaví hodnotu udávající, zda je obsah této třídy platný.
	 * 
	 * @param valid
	 *            Hodnota udávající, zda je obsah této třídy platný.
	 */
	public void setValid(boolean valid) {
		this.valid = valid;
	}
}

src/lase/servlet/ResultsBean.java
package lase.servlet;

import java.util.AbstractCollection;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.NoSuchElementException;

import lase.answersearch.Answer;
import lase.answersearch.AnswerGroup;
import lase.servlet.RequestQueue.LaseSearchResult;
import lase.util.Corpus.SourcePage;

/**
 * JavaBean obsahující výsledky hledání, tj. seznam všech nalezených odpovědí seřazený podle kvality, 
 * a zadanou otázku.
 *   
 * @author Rudolf Šíma
 *
 */
public class ResultsBean extends AbstractCollection<AnswerBeanList> {

	/**
	 * Seznam nalezených odpovědí seřazený podle kvality, tzn. první odpověď
	 * byla systémem LASE vyhodnocena jako nejlepší.
	 */
	public List<AnswerBeanList> answers;
	
	/**
	 * Otázka, kterou se systém pokoušel zodpovědět.
	 */
	private String question;

	/**
	 * Udává, zda tento bean obsahuje platné údaje, které mohou být zobrazeny.
	 */
	private boolean valid;
	
	/**
	 * Vytvoří novou prázdnou instanci výsledků hledání.
	 */
	public ResultsBean() {
		answers = new ArrayList<AnswerBeanList>(0);
		question = "";
		valid = false;
	}

	/**
	 * Vytvoří novou instanci a nastaví výsledky.
	 * 
	 * @param searchResult
	 *            Výsledk hledání.
	 */
	public ResultsBean(LaseSearchResult searchResult) {
		answers = new ArrayList<AnswerBeanList>(0);
		for (AnswerGroup ag : searchResult) {
			List<AnswerBean> beanList = new ArrayList<AnswerBean>();
			for (Answer a : ag) {
				AnswerBean bean = createAnswerBean(a); 
				beanList.add(bean);
			}
			answers.add(new AnswerBeanList(beanList));
		}
		question = searchResult.getQuestion();
		valid = true;
	}

	/**
	 * Vrací {@code true} obsahují-li tyto výsledky platné údaje, které mohou
	 * být zobrazeny, jinak brací {@code false}.
	 * 
	 * @return Vrací {@code true} obsahují-li tyto výsledky platné údaje, které
	 *         mohou být zobrazeny, jinak brací {@code false}.
	 */
	public boolean isValid() {
		return valid;
	}
	
	/* (non-Javadoc)
	 * @see java.util.AbstractCollection#isEmpty()
	 */
	@Override
	public boolean isEmpty() {
		return answers.isEmpty();
	}

	/**
	 * Vrací otázkou, kterou se systém pokoušel zodpovědět.
	 * 
	 * @return Vrací zodpovídanou otázku.
	 */
	public String getQuestion() {
		return question;
	}

	/**
	 * Vrací nejlepší skupinu odpovědí, tj. seznam všech nalezených shodných
	 * odpovědí, které byly vyhodnoceny jako nejlepší. (Odpovědi v seznamu se
	 * liší pouze svojí přesností.)
	 * 
	 * @return Vrací nejlepší skupinu odpovědí.
	 */
	public AnswerBeanList getBestGroup() {
		if (answers.isEmpty())
			throw new NoSuchElementException();
		return answers.get(0);
	}

	/**
	 * Vrací nejpravdivější a nejpřesnější nalezenou odpověď.
	 * 
	 * @return Vrací nejlepší odpověď.
	 */
	public AnswerBean getBestAnswer() {
		return getBestGroup().getBestAnswer();
	}

	/**
	 * Vytvoří {@link AnswerBean} na základě odpovědi v instanci třídy
	 * {@link Answer}, kterou vrátí systém LASE jako výsledek hledání.
	 * 
	 * @param answer
	 *            Výsledek hledání odpovědi systémem LASE.
	 * 
	 * @return Vrací odpověď nalezenou systémem laze jako instanci třídy
	 *         {@link AnswerBean}.
	 */
	private static AnswerBean createAnswerBean(Answer answer) {
		AnswerBean answerBean = new AnswerBean();
		if (answer == null) {
			answerBean.setNotFound(true);
		} else {
			SourcePage source = answer.getSource();
			answerBean.setSourceUrl(source.getUrl().toString());
			answerBean.setSourceTitle(source.getTitle());
			answerBean.setShortAnswer(answer.toString());
			answerBean.setLongAnswer(answer.getContext());
			answerBean.setValid(true);
		}
		return answerBean;
	}

	/**
	 * Vrací iterátor skupin sémanticky shodných odpovědí.
	 */
	@Override
	public Iterator<AnswerBeanList> iterator() {
		return answers.iterator();
		//return IterationUtils.readOnlyIterator(answers.iterator()); 
	}

	/**
	 * Vrací počet obsažených skupin sémanticky shodných shodných odpovědí.
	 */
	@Override
	public int size() {
		return answers.size();
	}
}

WebContent/about.jsp
<%@page session="true"  import='java.util.*'%>
<%@page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>

<jsp:include page="header.jsp" />

	<div class="text">
	<h1>Co je LASE</h1>

	LASE (Lingvo Answer Search Engine) je aplikace pro hledání odpovědí na internetu
	na dotazy kladené v přirozeném jazyce.<p/>
	Jedná se o webovou aplikaci poskytovanou webovým serverem, kterou lze obsluhovat
	prostřednictvím internetového prohlížeče.</p>

	</div>
</body>
</html>

WebContent/contact.jsp
<%@page session="true"  import='java.util.*'%>
<%@page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>

<jsp:include page="header.jsp" />

  <div class="text">
  <h1>Contact</h1>

  <h2>ZČU</h2><br/>
  Project LASE is developed by the <a href="http://www.kiv.zcu.cz/en/" alt="KIV ZCU" target="_blank">Department of Computer Science and Engineering at University of West Bohemia</a>.
  <p/>
  <h2>Team members</h2><p/>

  <h2 class="blue">Táriq Saleh Salem</h2><br/>
  <a href="mailto:tariq[at]students.zcu.cz">tariq[at]students.zcu.cz</a><p/>

  <h2 class="blue">Jan Rybák</h2><br/>
  <a href="mailto:rybak[at]students.zcu.cz">rybak[at]students.zcu.cz</a><p/>

  <h2 class="blue">Matyáš Latner</h2><br/>
  <a href="mailto:malatner[at]students.zcu.cz">malatner[at]students.zcu.cz</a><p/>
  <p/>
  <h2>Credits</h2><p/>

  <h2 class="blue">Jiří Fatka</h2><br/>
  <a href="mailto:fatkaj[at]students.zcu.cz">fatkaj[at]students.zcu.cz</a><p/>

  <h2 class="blue">Jaroslav Kohout</h2><br/>
  <a href="mailto:kohout[at]students.zcu.cz">kohout[at]students.zcu.cz</a><p/>
  <p/>
  <h2>Scientific supervision</h2><p/>

  <h2 class="blue">Miloslav Konopík</h2><br/>
  <a href="mailto:konopik[at]kiv.zcu.cz">konopik[at]kiv.zcu.cz</a><p/>

  <h2 class="blue">Ondřej Rohlík</h2><br/>
  <a href="mailto:rohlik[at]kiv.zcu.cz">rohlik[at]kiv.zcu.cz</a><p/>


  </div>
</body>
</html>

WebContent/documentation.jsp
<%@page session="true"  import='java.util.*'%>
<%@page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>

<jsp:include page="header.jsp" />

	<div class="text">
	<h1>Dokumentace</h1>

	Dokumentace je ke stažení v české a anglické verzi:
	<br/>----
	</div>
</body>
</html>

WebContent/header.jsp
<%@page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>

<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
<head>
     <meta name="robots" content="all, follow" />
     <meta http-equiv="content-type" content="text/html; charset=utf-8" />

     <meta name="author" content="El Goog Team, West Bohemian University in Pilsen" />
     <meta name="description" content="The application for finding answers to questions made in natural language on the Internet" />
     <meta name="keywords" content="LASE, natural language, question, search engine, askwiki" />

     <style type="text/css" media="screen">   @import url("style/style.css"); </style>
     <style type="text/css" media="screen">   @import url("style/toggle.css"); </style>
     <style type="text/css" media="handheld"> @import url("style/pda.css");   </style>
     <style type="text/css" media="print">    @import url("style/print.css"); </style>

	<script type="text/javascript" src="js/jquery-latest.pack.js"></script>
	<script type="text/javascript" src="js/jquery.toggleElements.pack.js"></script>

     <title>LASE - Looking for answers to questions in natural language"</title>

	 <script type="text/javascript">
		$(document).ready(function(){
			$('div.toggler').toggleElements( { fxAnimation:'show', fxSpeed:'slow', className:'toggler' } );
			$('div.toggler_grey').toggleElements( { fxAnimation:'show', fxSpeed:'slow', className:'toggler_grey' } );
			$('div.searchers').toggleElements( { fxAnimation:'show', fxSpeed:'slow', className:'searchers' } );
		});
		</script>
	 </script>
</head>

<body>
<div id="top">
	<div id="navi">
	<a href="./about.jsp">Co je LASE</a> | <a href="./help.jsp">Nápověda</a> | <a href="./contact.jsp">Kontakt</a>
	</div>
	<a href="./" alt="Home" title="Úvodní strana"><img src="img/lase_logo.gif" alt="LASE" title="LASE - Lingvo Answer Search Engine" id="lase_logo"></a>
</div>

<div id="search">
	<form action="./" name="questionForm" method="get" accept-charset="utf-8">
		<input type="text" name="q">
		<input type="image" id="submit" src="img/search_button.gif" value="SEARCH">
	</form>
</div>

WebContent/help.jsp
<%@page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>

<jsp:include page="header.jsp" />

	<div class="text">
	<h1>Nápověda</h1>

	<h2>Funkce</h2><p/>
	LASE (Lingvo Answer Search Engine) je aplikace pro hledání odpovědí na internetu
	na dotazy kladené v přirozeném jazyce.<p/>
	Po zadání dotazu do vyhledávacího pole se aplikace pokusí
	vyhledat odpovědi a zobrazit je uživateli v okně prohlížeče.<p/>

	<h2>Otázky</h2><p/>
	LASE je navržen k vyhledávání otázek v českém jazyce začínajících na slova:
	<ul>
		<li>Kdo</li>
		<li>Kde</li>
		<li>Kdy</li>
		<li>Co</li>
		<li>Proč</li>
	</ul>
	Na jinak položené otázky nedokáže vyhledat odpověď. V případě, že ani na správně
	položenou otázku nenajde odpověď, pokuste se o jinou formulaci otázky.<p/>
	Pro zpřesnění odpovědi je vhodné klást otázky spíše konkrétně než obecně, například
	je vhodnější zadat <span class="i">"Kde leží Paříž"</span> než <span class="i">"Kde je Paříž"</span>.<p/>

	<h2>Hodnocení</h2><p/>
	U každé nalezené odpovědi jsou zobrazena tři tlačítka pro vyhodnocení Vašeho
	názoru na správnost odpovědi. Váš názor nám pomůže při ladění a zlepšování
	aplikace.

	</div>
</body>
</html>

WebContent/index.jsp
<%@page contentType="text/html; charset=UTF-8" %> 
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>


<%@page import="java.util.List"%>
<%@page import="lase.servlet.AnswerBeanList" %>
<%@page import="lase.servlet.AnswerBean" %>
<%@page import="lase.servlet.ResultsBean" %>

<jsp:include page="header.jsp" />

<script language="javascript">
function explain(divId, aId) {
	var expl = document.getElementById(divId);
	var link = document.getElementById(aId);
	if (expl.style.visibility != 'visible') {
		expl.style.visibility = 'visible';
		expl.style.height = 'auto';
		link.innerHTML = "skrýt vysvětlení";
	} else {
		expl.style.visibility = 'hidden';
		expl.style.height = '0px';
		link.innerHTML = "vysvětlit";
	}
}
</script>

<c:if test="${results.valid}">
<div class="answer">
<c:choose>
	<c:when test="${empty results}">
	Odpověď na otázku "<c:out escapeXml="true" value="${results.question}" />" nebyla nalezena.
	</c:when>
<c:otherwise>
	<p style="color:gray">Otázka: <c:out escapeXml="true" value="${results.question}" /></p>
	<div class="grey">Odpověď: <strong><c:out escapeXml="true" value="${results.bestAnswer.shortAnswer}" /></strong>
	<a href="${results.bestAnswer.sourceUrl}">zdroj</a><span class="linksep"> | </span><a href="javascript:explain('bestAnsExpl', 'bestAnsExplLink')" id="bestAnsExplLink">vysvětlit</a><br/>
	<div id="bestAnsExpl" class="explanation">
		<c:forEach var="a" items="${results.bestGroup}">
		<a href="${a.sourceUrl}">
		<c:out value="${a.longAnswer}"></c:out><br/>
		</a>
		</c:forEach>
	</div>
	<span style="font-size:8pt"><c:out escapeXml="true" value="${results.bestAnswer.longAnswer}"/></span>
	</div>
	<input type="button" value="správně" onclick="location.href='rate?q=${results.question}&a=${results.bestAnswer.shortAnswer}&r=T'">
	<input type="button" value="špatně" onclick="location.href='rate?q=${results.question}&a=${results.bestAnswer.shortAnswer}&r=F'">
	<input type="button" value="nevím" onclick="location.href='rate?q=${results.question}&a=${results.bestAnswer.shortAnswer}&r=0'">
	<c:if test="${fn:length(results) gt 1}">
	<hr/>
	<div style="color:gray;">Další nalezené odpovědi</div>
	<div style="margin-left:50px">
	
	<c:forEach var="answerList" items="${results}" varStatus="status">
		<c:if test="${other}">
		<c:out escapeXml="true" value="${answerList.bestAnswer.shortAnswer}" /> <a href="${answerList.bestAnswer.sourceUrl}">zdroj</a><span class="linksep"> | </span><a href="javascript:explain('bestAnsExpl${status.count}', 'bestAnsExplLink${status.count}')" id="bestAnsExplLink${status.count}">vysvětlit</a><span class="linksep"> | </span><a href="rate?q=${results.question}&a=${answerList.bestAnswer.shortAnswer}&r=OT">Tato odpověď je správná</a><br/>
		<div id="bestAnsExpl${status.count}" class="explanation">
			<c:forEach var="a" items="${answerList}">
				<a href="${a.sourceUrl}">
				<c:out value="${a.longAnswer}"></c:out><br/>
				</a>
			</c:forEach>
		</div>
		</c:if>
		<c:set var="other" value="true" />
	</c:forEach>
	</div>
	</c:if>
</c:otherwise>
</c:choose>
</div>
</c:if>

<c:choose>
<c:when test="${not empty results.question}">

<!-- <div style="margin-left:120px"> -->
<!-- <iframe src="http://www.google.cz/search?q="${results.question}" hspace="100"></iframe> -->
<iframe src="http://www.bing.com/search?q=${results.question}" hspace="100" ></iframe>
<!-- </div> -->

</c:when>
<c:otherwise>

<div id="main">
	<div class="text toLeft">
	<h2>Ukázkové otázky / Sample questions</h2>
	<p/>
	<ul style="float: left;">
		<li><a href="?q=Kdy se narodil Karel IV.?" class="question">
		Kdy se narodil Karel IV.?</a><br/>
		<span class="i">When Karel IV. was born?</span>
		</li>

		<li><a href="./?q=Kdy byl založen Microsoft?" class="question">
		Kdy byl založen Microsoft?</a><br/>
		<span class="i">When was Microsoft founded?</span>
		</li>

		<li><a href="?q=Kdo byl první prezident USA?" class="question">
		Kdo byl první prezident USA?</a><br/>
		<span class="i">Who was the first president of USA?</span>
		</li>

		<li><a href="?q=Kde se nachází Kolumbie?" class="question">
		Kde se nachází Kolumbie?</a><br/>
		<span class="i">Where is the Country of Columbia?</span>
		</li>

		<li><a href="?q=Co je to autoportrét?" class="question">
		Co je to autoportrét?</a><br/>
		<span class="i">What does it mean autoportrait?</span>
		</li>

		<li><a href="?q=Kdy zemřel Jan Hus?" class="question">
		Kdy zemřel Jan Hus?</a><br/>
		<span class="i">When did Jan Hus die?</span>
		</li>

		<li><a href="?q=Kdo je nejlepší kuchař?" class="question">
		Kdo je nejlepší kuchař?</a><br/>
		<span class="i">Who is the best cook?</span>
		</li>

		<li><a href="?q=kde je O2 arena?" class="question">
		Kde je 02 Arena?</a><br/>
		<span class="i">Where is situated 02 Arena?</span>
		</li>

		<li><a href="?q=Kdo objevil Ameriku?" class="question">
		Kdo objevil Ameriku?</a><br/>
		<span class="i">Who discovered America?</span>
		</li>

	</ul>
	<ul style="float: right;position: relative; right: 80px;">
		<li><a href="?q=Kde je Eiffelova věž?" class="question">
		Kde je Eiffelova věž?</a><br/>
		<span class="i">Where is the Eiffel Tower?</span>
		</li>

		<li><a href="?q=Kdo byl prezidentem ČSR?" class="question">
		Kdo byl prezidentem ČSR?</a><br/>
		<span class="i">Who was the president of ČSR?</span>
		</li>

		<li><a href="?q=Kdy se narodil Karel Gott?" class="question">
		Kdy se narodil Karel Gott?</a><br/>
		<span class="i">When was Karel Gott born?</span>
		</li>

		<li><a href="?q=Kde je Budapešť?" class="question">
		Kde je Budapešť?</a><br/>
		<span class="i">Where is Budapest?</span>
		</li>

		<li><a href="?q=Kdo vynalezl dynamit?" class="question">
		Kdo vynalezl dynamit?</a><br/>
		<span class="i">Who invented dynamit?</span>
		</li>

		<li><a href="?q=Kdy vznikla Česká republika?" class="question">
		Kdy vznikla Česká republika?</a><br/>
		<span class="i">When was Czech Republic independent?</span>
		</li>

		<li><a href="?q=Kde sídlí NATO" class="question">
		Kde sídlí NATO?</a><br/>
		<span class="i">Where is NATO?</span>
		</li>

		<li><a href="?q=Kdo je prezidentem USA?" class="question">
		Kdo je prezidentem USA?</a><br/>
		<span class="i">Who is the president of USA?</span>
		</li>

		<li><a href="?q=Kdy se narodil Barack Obama?" class="question">
		Kdy se narodil Barack Obama?</a><br/>
		<span class="i">When was Barack Obama born?</span>
		</li>

	</ul>
	<div style="clear:both;"></div>
	</div>
	</div>


</c:otherwise>
</c:choose>

</body>
</html>

WebContent/wait.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>LASE - Looking for answers to questions in natural language</title>
</head>
<body>
<div style="width:100%; text-align:center; margin-top:100px">
<p style="font-family:Arial; font-size:10pt">
<c:out value="${message}" />
<p>
</div>
</body>
</html>